#!/usr/bin/env tsx
/**
 * Regenerate sources/_index/{by-topic,by-date}.md from capture frontmatter.
 *
 * Usage:
 *   npm run index:sources
 */

import { readdir, readFile, writeFile, mkdir, stat } from "node:fs/promises";
import { join, relative, resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import yaml from "js-yaml";

interface Capture {
  file: string;
  url: string | null;
  captured_at: string | null;
  source_type: string | null;
  source_id: string | null;
  title_at_capture: string | null;
  evidence_class: string | null;
  topics: string[];
}

const FRONTMATTER_RE = /^---\n([\s\S]*?)\n---/;

async function walk(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true });
  const results: string[] = [];
  for (const entry of entries) {
    if (entry.name.startsWith("_") || entry.name.startsWith(".")) continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...(await walk(full)));
    } else if (entry.isFile() && entry.name.endsWith(".md")) {
      results.push(full);
    }
  }
  return results;
}

async function parseCapture(filePath: string, sourcesRoot: string): Promise<Capture | null> {
  const text = await readFile(filePath, "utf8");
  const match = text.match(FRONTMATTER_RE);
  if (!match) return null;
  let fm: Record<string, unknown>;
  try {
    fm = (yaml.load(match[1]) as Record<string, unknown>) ?? {};
  } catch (e) {
    console.warn(`[index] yaml parse failed for ${filePath}: ${(e as Error).message}`);
    return null;
  }
  const topics = Array.isArray(fm.topics) ? (fm.topics as unknown[]).filter((t): t is string => typeof t === "string") : [];
  return {
    file: relative(sourcesRoot, filePath),
    url: (fm.url as string) ?? null,
    captured_at: (fm.captured_at as string) ?? null,
    source_type: (fm.source_type as string) ?? null,
    source_id: (fm.source_id as string) ?? null,
    title_at_capture: (fm.title_at_capture as string) ?? null,
    evidence_class: (fm.evidence_class as string) ?? null,
    topics,
  };
}

function renderEntry(c: Capture, sourcesRoot: string): string {
  const title = c.title_at_capture ?? c.file;
  const evidence = c.evidence_class ? ` **(${c.evidence_class})**` : "";
  const type = c.source_type ? ` · _${c.source_type}_` : "";
  return `- [${title}](../${c.file})${evidence}${type}`;
}

function renderByTopic(captures: Capture[], sourcesRoot: string): string {
  const byTopic = new Map<string, Capture[]>();
  const untagged: Capture[] = [];
  for (const c of captures) {
    if (c.topics.length === 0) {
      untagged.push(c);
      continue;
    }
    for (const t of c.topics) {
      if (!byTopic.has(t)) byTopic.set(t, []);
      byTopic.get(t)!.push(c);
    }
  }

  const header = `<!-- generated by sources/_scripts/build-index.ts — do not edit -->\n\n# Sources by Topic\n\n${captures.length} captures across ${byTopic.size} topics. Regenerate with \`npm run index:sources\`.\n\n`;

  const sortedTopics = [...byTopic.keys()].sort();
  const sections = sortedTopics
    .map((topic) => {
      const items = byTopic.get(topic)!.sort((a, b) => (b.captured_at ?? "").localeCompare(a.captured_at ?? ""));
      return `## ${topic}\n\n${items.map((c) => renderEntry(c, sourcesRoot)).join("\n")}\n`;
    })
    .join("\n");

  const untaggedSection = untagged.length
    ? `\n## (untagged)\n\n${untagged.map((c) => renderEntry(c, sourcesRoot)).join("\n")}\n`
    : "";

  return header + sections + untaggedSection;
}

function renderByDate(captures: Capture[], sourcesRoot: string): string {
  const sorted = [...captures].sort((a, b) =>
    (b.captured_at ?? "").localeCompare(a.captured_at ?? ""),
  );
  const header = `<!-- generated by sources/_scripts/build-index.ts — do not edit -->\n\n# Sources by Date\n\n${captures.length} captures, newest first. Regenerate with \`npm run index:sources\`.\n\n`;

  const byDate = new Map<string, Capture[]>();
  for (const c of sorted) {
    const d = c.captured_at ?? "unknown";
    if (!byDate.has(d)) byDate.set(d, []);
    byDate.get(d)!.push(c);
  }
  const sections = [...byDate.keys()]
    .map((date) => {
      const items = byDate.get(date)!;
      return `## ${date}\n\n${items.map((c) => renderEntry(c, sourcesRoot)).join("\n")}\n`;
    })
    .join("\n");
  return header + sections;
}

async function main() {
  const scriptDir = dirname(fileURLToPath(import.meta.url));
  const sourcesRoot = resolve(scriptDir, "..");
  const indexDir = resolve(sourcesRoot, "_index");

  const files = await walk(sourcesRoot);
  const captures: Capture[] = [];
  for (const f of files) {
    const c = await parseCapture(f, sourcesRoot);
    if (c) captures.push(c);
    else console.warn(`[index] skipped (no frontmatter): ${relative(sourcesRoot, f)}`);
  }
  console.log(`[index] parsed ${captures.length} captures`);

  await mkdir(indexDir, { recursive: true });

  const byTopicPath = join(indexDir, "by-topic.md");
  await writeFile(byTopicPath, renderByTopic(captures, sourcesRoot), "utf8");
  console.log(`[index] wrote ${relative(sourcesRoot, byTopicPath)}`);

  const byDatePath = join(indexDir, "by-date.md");
  await writeFile(byDatePath, renderByDate(captures, sourcesRoot), "utf8");
  console.log(`[index] wrote ${relative(sourcesRoot, byDatePath)}`);
}

main().catch((e) => {
  console.error(`[index] error: ${(e as Error).message}`);
  process.exit(1);
});
